# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Alamgir
tagline:          'blog'
description:      "a blog that contain reading notes for various books I've read"
baseurl:          /blog
author:
  name:           'Alamgir Qazi'
  url:            https://twitter.com/alamgirqazi

paginate:         100
gems: [jekyll-paginate]
# Custom vars
version:          2.0.0

github:
   repo:           https://github.com/alamgirqazi/blog
